---
title: "Visualization"
subtitle: "Part 2"
output: github_document
---

```{r setup}
library(tidyverse)
library(patchwork)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)
```

## Labels: adding text to explain
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    tittle = "Temp plot",
    x = "Min daily temp (C)",
    y = "Max daily tem (C)",
    caption = "Data from the anoaa package; temp in 2017."
  )
```

## Scales: 

Start with the same plot: x and y scales
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    tittle = "Temp plot",
    x = "Min daily temp (C)",
    y = "Max daily tem (C)",
    caption = "Data from the anoaa package; temp in 2017."
  ) +
  #continuous can be changed to discrete for categorical data.
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15C", "0C", "15C")
  ) +
  #scale_y_continuous( trans = "sqrt" /"log")
  scale_y_continuous(position = "right")
```

Look at color scales:
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    tittle = "Temp plot",
    x = "Min daily temp (C)",
    y = "Max daily tem (C)",
    caption = "Data from the anoaa package; temp in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE)
# scale_color_hue(h = c(100,300))
```

## Themes

shift the legend

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    tittle = "Temp plot",
    x = "Min daily temp (C)",
    y = "Max daily tem (C)",
    caption = "Data from the anoaa package; temp in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE) +
  theme(legend.position = "bottom")
```

Change the overall theme

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    tittle = "Temp plot",
    x = "Min daily temp (C)",
    y = "Max daily tem (C)",
    caption = "Data from the anoaa package; temp in 2017."
  ) +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE) +
  #theme_bw()
  #theme_classic()
  #ggthemes::theme_economist()
  #ggthemes::theme_excel()
  theme_minimal() +
  theme(legend.position = "bottom")
#the theme option need to go after changeing the overall theme
```

## Setting options

```{r, eval=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

















